// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: schema/grpc_websocket_api_gateway.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L2OrderBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Size     uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Interval uint32 `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *L2OrderBookRequest) Reset() {
	*x = L2OrderBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_grpc_websocket_api_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2OrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2OrderBookRequest) ProtoMessage() {}

func (x *L2OrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_grpc_websocket_api_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2OrderBookRequest.ProtoReflect.Descriptor instead.
func (*L2OrderBookRequest) Descriptor() ([]byte, []int) {
	return file_schema_grpc_websocket_api_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *L2OrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *L2OrderBookRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *L2OrderBookRequest) GetInterval() uint32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type L2OrderBookItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume uint64 `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *L2OrderBookItem) Reset() {
	*x = L2OrderBookItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_grpc_websocket_api_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2OrderBookItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2OrderBookItem) ProtoMessage() {}

func (x *L2OrderBookItem) ProtoReflect() protoreflect.Message {
	mi := &file_schema_grpc_websocket_api_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2OrderBookItem.ProtoReflect.Descriptor instead.
func (*L2OrderBookItem) Descriptor() ([]byte, []int) {
	return file_schema_grpc_websocket_api_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *L2OrderBookItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *L2OrderBookItem) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type L2OrderBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid    []*L2OrderBookItem     `protobuf:"bytes,2,rep,name=bid,proto3" json:"bid,omitempty"`
	Ask    []*L2OrderBookItem     `protobuf:"bytes,3,rep,name=ask,proto3" json:"ask,omitempty"`
	Time   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *L2OrderBook) Reset() {
	*x = L2OrderBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_grpc_websocket_api_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2OrderBook) ProtoMessage() {}

func (x *L2OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_schema_grpc_websocket_api_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2OrderBook.ProtoReflect.Descriptor instead.
func (*L2OrderBook) Descriptor() ([]byte, []int) {
	return file_schema_grpc_websocket_api_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *L2OrderBook) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *L2OrderBook) GetBid() []*L2OrderBookItem {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *L2OrderBook) GetAsk() []*L2OrderBookItem {
	if x != nil {
		return x.Ask
	}
	return nil
}

func (x *L2OrderBook) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_schema_grpc_websocket_api_gateway_proto protoreflect.FileDescriptor

var file_schema_grpc_websocket_api_gateway_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x77, 0x65,
	0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x12, 0x4c, 0x32,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x3f, 0x0a, 0x0f, 0x4c, 0x32, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x4c, 0x32,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x22, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x03, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x52, 0x0a, 0x17, 0x47, 0x72, 0x70,
	0x63, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x70, 0x69, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x12, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x32, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x13, 0x2e, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x4c, 0x32,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x76, 0x61, 0x6e,
	0x62, 0x75, 0x6c, 0x79, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x77, 0x65, 0x62, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_grpc_websocket_api_gateway_proto_rawDescOnce sync.Once
	file_schema_grpc_websocket_api_gateway_proto_rawDescData = file_schema_grpc_websocket_api_gateway_proto_rawDesc
)

func file_schema_grpc_websocket_api_gateway_proto_rawDescGZIP() []byte {
	file_schema_grpc_websocket_api_gateway_proto_rawDescOnce.Do(func() {
		file_schema_grpc_websocket_api_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_grpc_websocket_api_gateway_proto_rawDescData)
	})
	return file_schema_grpc_websocket_api_gateway_proto_rawDescData
}

var file_schema_grpc_websocket_api_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_grpc_websocket_api_gateway_proto_goTypes = []interface{}{
	(*L2OrderBookRequest)(nil),    // 0: L2OrderBookRequest
	(*L2OrderBookItem)(nil),       // 1: L2OrderBookItem
	(*L2OrderBook)(nil),           // 2: L2OrderBook
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_schema_grpc_websocket_api_gateway_proto_depIdxs = []int32{
	1, // 0: L2OrderBook.bid:type_name -> L2OrderBookItem
	1, // 1: L2OrderBook.ask:type_name -> L2OrderBookItem
	3, // 2: L2OrderBook.time:type_name -> google.protobuf.Timestamp
	0, // 3: GrpcWebsocketApiGateway.GetL2OrderBook:input_type -> L2OrderBookRequest
	2, // 4: GrpcWebsocketApiGateway.GetL2OrderBook:output_type -> L2OrderBook
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schema_grpc_websocket_api_gateway_proto_init() }
func file_schema_grpc_websocket_api_gateway_proto_init() {
	if File_schema_grpc_websocket_api_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_grpc_websocket_api_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2OrderBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_grpc_websocket_api_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2OrderBookItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_grpc_websocket_api_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2OrderBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_grpc_websocket_api_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_grpc_websocket_api_gateway_proto_goTypes,
		DependencyIndexes: file_schema_grpc_websocket_api_gateway_proto_depIdxs,
		MessageInfos:      file_schema_grpc_websocket_api_gateway_proto_msgTypes,
	}.Build()
	File_schema_grpc_websocket_api_gateway_proto = out.File
	file_schema_grpc_websocket_api_gateway_proto_rawDesc = nil
	file_schema_grpc_websocket_api_gateway_proto_goTypes = nil
	file_schema_grpc_websocket_api_gateway_proto_depIdxs = nil
}
